/*
 * plutonic - experimental RISC-V kernel
 *
 * Copyright (C) 2026 krakenlake
 *
 */

#ifndef PLUTONIC_TRAP_H
#define PLUTONIC_TRAP_H

#include "config.h"

#define TIMER_INTERVAL		10000000

#ifdef HW_QEMU
	#define MTIMECMP		0x2004000		# QEMU CLINT 0x2000000 + 0x4000 + 8*(hart_id)
#endif

#define SCAUSE_MISALIGNED_FETCH			0
#define SCAUSE_FAULT_FETCH				1
#define SCAUSE_ILLEGAL_INSTRUCTION		2
#define SCAUSE_BREAKPOINT				3
#define SCAUSE_MISALIGNED_LOAD			4
#define SCAUSE_FAULT_LOAD				5
#define SCAUSE_MISALIGNED_STORE			6
#define SCAUSE_FAULT_STORE				7
#define SCAUSE_USER_ECALL				8
#define SCAUSE_SUPERVISOR_ECALL			9
#define SCAUSE_HYPERVISOR_ECALL			10
#define SCAUSE_MACHINE_ECALL			11
#define SCAUSE_FETCH_PAGE_FAULT			12
#define SCAUSE_LOAD_PAGE_FAULT			13
#define SCAUSE_RESERVED_14				14
#define SCAUSE_STORE_PAGE_FAULT			15
#define SCAUSE_RESERVED_16				16
#define SCAUSE_RESERVED_17				17
#define SCAUSE_SOFTWARE_CHECK			18
#define SCAUSE_HARDWARE_ERROR			19

#endif /* PLUTONIC_TRAP_H */
